mwouts/itables

- CHANGELOG.md
- HISTORY.md
- README.md
- itables/downsample.py
- itables/javascript.py
- itables/javascript/eval_functions.js
- itables/javascript/load_datatables_connected.js
- itables/options.py
- itables/version.py
- requirements-dev.txt
- setup.py
- tests/test_downsample.py
- tests/test_notebooks.py
- Large tables are downsampled (Fixes #2)
- Javascript code moved to Javascript files
- Tables with many columns are now well rendered (Fixes #5)
> Version 0.2

- .travis.yml
- itables/javascript.py
- setup.py
- tests/test_javascript.py
resolves https://github.com/mwouts/itables/issues/14
> add safety in case pandas display.max_columns is None

- CHANGELOG.md
- itables/version.py
- setup.py
> Add 'require_config.js' to the pip package

- CHANGELOG.md
- docs/advanced_parameters.md
- itables/options.py
- itables/version.py
> No fixed column width

- .pre-commit-config.yaml
- README.md
- docs/advanced_parameters.md
- docs/changelog.md
- docs/downsampling.md
- docs/quick_start.md
- docs/sample_dataframes.md
- itables/__init__.py
- itables/html/column_filters/initComplete.js
- itables/html/column_filters/pre_dt_code.js
- itables/html/datatables_template.html
- itables/html/datatables_template_connected.html
- itables/html/style.css
- itables/javascript.py
- itables/options.py
- itables/version.py
- tests/test_json_dumps.py
> Individual column filters

- docs/changelog.md
- itables/downsample.py
- itables/javascript.py
- itables/version.py
- tests/test_downsample.py
> Downsample on rows (resp. columns) when the table has many rows (resp.columns)

- docs/changelog.md
- docs/supported_editors.md
- environment.yml
- itables/__init__.py
- itables/javascript.py
- itables/version.py
- requirements-dev.txt
- tests/sample_python_apps/itables_in_a_shiny_app.py
- tests/sample_python_apps/itables_in_a_shiny_app_with_tabs.py
- tests/test_javascript.py
- tests/test_sample_python_apps.py
> Itables works with Shiny for Python

- docs/advanced_parameters.md
- docs/changelog.md
- itables/javascript.py
- itables/sample_dfs.py
- itables/version.py
> Preserve the order of rows by default

- docs/changelog.md
- docs/sample_dataframes.md
- itables/javascript.py
- itables/sample_dfs.py
- itables/version.py
> Support nullable types

- README.md
- docs/quick_start.md
> Add conda install instructions in README and docs

- docs/advanced_parameters.md
- docs/changelog.md
- docs/downsampling.md
- docs/quick_start.md
- docs/sample_dataframes.md
- itables/options.py
- itables/version.py
> Use autoWidth = False rather than scrollX = True

- .github/workflows/continuous-integration.yml
- .pre-commit-config.yaml
- docs/changelog.md
- itables/downsample.py
- itables/javascript.py
- itables/sample_dfs.py
- itables/utils.py
- itables/version.py
- requirements-dev.txt
- setup.py
- tests/test_changelog.py
- tests/test_connected_notebook_is_small.py
- tests/test_sample_dfs.py
- tests/test_update_samples.py
> Py2 support

- docs/changelog.md
- itables/datatables_format.py
- itables/javascript.py
- itables/sample_dfs.py
- setup.cfg
- tests/test_datatables_format.py
- tests/test_sample_dfs.py
> Use `pandas.io.formats.format` to format complex types

- docs/changelog.md
- itables/datatables_format.py
- itables/options.py
- tests/test_datatables_format.py
- tests/test_sample_dfs.py
and introduce `warn_on_unexpected_types`
Follow-up on #112 #117
> Further simplify _format_column

- README.md
- docs/changelog.md
- docs/downsampling.md
- itables/downsample.py
- itables/javascript.py
- itables/sample_dfs.py
- itables/version.py
- tests/test_downsample.py
- tests/test_sample_dfs.py
> Faster downsampling, more discrete downsampling warning

- .pre-commit-config.yaml
- pyproject.toml
Fixes #123 and #124. Many thanks to @Anselmoo!
> Add requests (and pathlib) to the build requirements

- docs/changelog.md
- itables/html/datatables_template_connected.html
- itables/version.py
- setup.py
> Improve support for dark themes

- docs/changelog.md
- itables/options.py
> Change default style to "table-layout:auto"

- docs/changelog.md
- tests/test_documentation_notebooks_run.py
This PR might help to increase the coverage
> Test the documentation notebooks

- docs/changelog.md
- docs/sample_dataframes.md
- itables/javascript.py
- itables/sample_dfs.py
> Allow duplicated column and index names

- itables/javascript.py
This is a small refactoring to follow up on #136
> New function safe_reset_index

- docs/advanced_parameters.md
- docs/changelog.md
- itables/javascript.py
- itables/options.py
> No row sorting by default

- docs/sample_dataframes.md
- itables/sample_dfs.py
- tests/test_sample_dfs.py
> Do not sort tables that have a categorical index

- docs/changelog.md
- itables/options.py
- itables/version.py
- pyproject.toml
- setup.py
> Add setuptools as the build backend + fix a typo on style

- docs/changelog.md
- docs/sample_dataframes.md
- itables/datatables_format.py
- itables/javascript.py
- itables/sample_dfs.py
- itables/version.py
- tests/test_datatables_format.py
> Align table content with header

- docs/changelog.md
- itables/javascript.py
- itables/sample_dfs.py
- itables/version.py
- setup.py
> Fix dependencies

- docs/changelog.md
- itables/javascript.py
- itables/version.py
- tests/conftest.py
- tests/test_javascript.py
- tests/test_sample_dfs.py
- tests/test_update_samples.py
> lengthMenu can be either a 1D or 2D array

- .pre-commit-config.yaml
- docs/advanced_parameters.md
- docs/changelog.md
- docs/custom_css.md
- docs/downsampling.md
- docs/quick_start.md
- docs/sample_dataframes.md
- itables/version.py
We update the hooks to solve an issue on the [CI](https://github.com/mwouts/itables/actions/runs/4368197697/jobs/7640476472).
> Update the pre-commit hooks

- docs/advanced_parameters.md
- docs/changelog.md
- docs/quick_start.md
- itables/sample_dfs.py
With this PR we include images (flags from https://www.countryflags.com) in the sample country dataframe.
The sample df will then look like this:
Closes #158
> Country flags

- docs/changelog.md
- itables/html/datatables_template.html
- itables/html/initialize_offline_datatable.html
Seems promising :smile: Thanks @fwouts !
> Use a pending promise to automatically wait for DataTable to be initialised

- .github/workflows/continuous-integration.yml
- README.md
- codecov.yml
- docs/_toc.yml
- docs/changelog.md
- docs/polars_dataframes.md
- docs/quick_start.md
- environment.yml
- itables/datatables_format.py
- itables/downsample.py
- itables/javascript.py
- itables/sample_dfs.py
- setup.py
- tests/conftest.py
- tests/test_datatables_format.py
- tests/test_documentation_notebooks_run.py
- tests/test_downsample.py
- tests/test_polars.py
- tests/test_sample_dfs.py
- tests/test_update_samples.py
> Support Polars DataFrames

- README.md
- docs/changelog.md
- docs/quick_start.md
- itables/sample_dfs.py
- itables/version.py
**Fixed**
- We have addressed the `window.initializeDataTable` is not a function error when a notebook is reloaded
([#160](https://github.com/mwouts/itables/issues/160), [#163](https://github.com/mwouts/itables/issues/163)). Many thanks again to [François Wouts](https://github.com/fwouts) for providing the right fix!
**Added**
- Polars DataFrames are supported ([#159](https://github.com/mwouts/itables/issues/159))
- We have added an example to show how to include images in tables ([#158](https://github.com/mwouts/itables/issues/158))
- We have added links and images (flags from https://flagpedia.net) to the sample countries df ([#158](https://github.com/mwouts/itables/issues/158)).
**Changed**
- We have updated the pre-commit hooks
> Version 1.5.0

- docs/advanced_parameters.md
> Document the showIndex argument/option

- docs/changelog.md
- itables/datatables_format.py
- itables/sample_dfs.py
- itables/version.py
> Fix overflow error when displaying a Polars table containing unsigned integers

- docs/_toc.yml
- docs/advanced_parameters.md
- docs/changelog.md
- docs/pandas_style.md
- itables/javascript.py
- itables/sample_dfs.py
- itables/version.py
- requirements-dev.txt
- tests/test_sample_dfs.py
> Add support for Pandas style

- .github/workflows/continuous-integration.yml
- README.md
- codecov.yml
- docs/changelog.md
- docs/quick_start.md
- itables/javascript.py
- itables/version.py
- tests/test_documentation_notebooks_run.py
- tests/test_sample_dfs.py
> Make the indirect dependency on jinja2 optional

- docs/changelog.md
- itables/javascript.py
- itables/version.py
- tests/test_html_in_table_header.py
> Allow html in columns

- docs/changelog.md
- itables/html/itables.css
- itables/javascript.py
- itables/version.py
- tests/test_javascript.py
Closes #103, #156, #232
Closes #233
> Fix dark mode in VS Code and Colab

- docs/changelog.md
- itables/html/init_datatables.html
- itables/javascript.py
- tests/test_connected_notebook_is_small.py
> Set a dark class for the dark mode

- docs/changelog.md
- itables/javascript.py
> Display Pandas Style objects using sparse_index=False

- docs/changelog.md
- itables/dt_for_itables/README.md
- itables/dt_for_itables/package-lock.json
- itables/dt_for_itables/package.json
- itables/html/datatables_template.html
- itables/utils.py
- pyproject.toml
- tests/test_javascript.py
> Update datatables-net to version 2.0.5

- docs/changelog.md
- docs/downsampling.md
- itables/downsample.py
- itables/options.py
- tests/test_downsample.py
> maxBytes can be a string

- docs/changelog.md
- packages/itables_for_streamlit/package-lock.json
Fix https://github.com/mwouts/itables/security/dependabot/1
> Fix dependabot alert #1

- docs/changelog.md
- src/itables/datatables_format.py
- src/itables/version.py
- tests/test_datatables_format.py
- tests/test_polars.py
> Improve the detection of large integers

- LICENSE
- docs/changelog.md
- src/itables/downsample.py
- src/itables/javascript.py
- src/itables/version.py
- tests/test_downsample.py
- tests/test_shiny.py
> Downsampled tables might have a odd row count

- apps/dash/3_update_table.py
- apps/dash/assets/style.css
- packages/itables_for_dash/src/lib/fragments/ITable.react.js
> Fix: allow fewer columns in ITable for Dash

- .github/workflows/publish.yml
The build with `python -m build` failed, cf. https://github.com/mwouts/itables/actions/runs/14277644963
> Build the package with hatch

- README.md
- docs/quarto/quarto_html.qmd
- docs/quarto/quarto_revealjs.qmd
- docs/quick_start.md
- src/itables/datatables_format.py
- tests/test_connected_notebook_is_small.py
- Fix the Quarto examples
- Add a badge for the Dash component
- Add a paragraph about the MIT license.
> Update the documentation

- .github/workflows/publish-book.yml
- docs/_config.yml
- environment.yml
Some documentation pages were renamed. This PR adds redirections from the old names to the new names.
> Add redirects

- docs/_toc.yml
- docs/changelog.md
- docs/options/text_in_header_can_be_selected.md
- packages/dt_for_itables/CHANGELOG.md
- packages/dt_for_itables/package-lock.json
- packages/dt_for_itables/package.json
- packages/dt_for_itables/src/index.js
- packages/itables_anywidget/package-lock.json
- packages/itables_for_dash/package-lock.json
- packages/itables_for_streamlit/package-lock.json
- src/itables/utils.py
- src/itables/version.py
This fixes an interaction with column_filters="headers"
> Improve text_in_header_can_be_selected, add documentation

- docs/changelog.md
- docs/options/allow_html.md
- docs/options/options.md
- docs/options/order.md
- docs/options/scroll_x.md
- docs/options/scroll_y.md
- docs/pandas_style.md
- packages/dt_for_itables/CHANGELOG.md
- packages/dt_for_itables/src/index.js
- src/itables/datatables_format.py
- src/itables/javascript.py
- src/itables/typing.py
- src/itables/version.py
- tests/test_polars.py
> Version 2.4.0

- README.md
- docs/changelog.md
- docs/py/quick_start.py
- docs/quick_start.md
- pyproject.toml
- src/itables/version.py
> Add Typed and Dash classifiers

- docs/changelog.md
- docs/options/length_menu.md
- docs/py/options/length_menu.py
- src/itables/options.py
- src/itables/typing.py
> Add type hints for pageLength

- docs/changelog.md
- pyproject.toml
- src/itables/datatables_format.py
- src/itables/downsample.py
- src/itables/javascript.py
- src/itables/options.py
- src/itables/sample_dfs.py
- src/itables/shiny.py
- src/itables/streamlit.py
- src/itables/typing.py
- src/itables/utils.py
- src/itables/version.py
- src/itables/widget/__init__.py
- src/itables_for_dash/__init__.py
- src/itables_for_dash/properties.py
> Version 2.4.2
