mwouts/itables

setup.py
Make setup.py match the items from requirements.txt since setuptools doesn't read the latter.
=> Add IPython to setup.py install_requires

README.md
This PR adds an example of centered cells to the README.
Closes #22
=> Cell alignment is available through cell classes

CHANGELOG.md, itables/datatables_template.html, itables/javascript.py, itables/javascript/load_datatables_connected.js
Many thanks to @fwouts for his precious help on this!
Fixes #3, #4, #26, #40
=> Load datatables.net with an ES import when `require.js` is not available

CHANGELOG.md, environment.yml, itables/javascript.py
We use `pandas.to_html` to generate the table header, as we did in versions < 0.4.2.
This improves the rendering of tables with multiindex columns #63
=> Improve multiindex columns

docs/changelog.md, itables/javascript.py, itables/version.py, tests/test_sample_dfs.py
In my project i use sql statements in order to obtain pandas dataframes. In one queries I selected two columns with the same name from different tables and I got this error:
I changed the indexing method to avoid this kind of behaviour caused by pandas.
=> solve bug caused by df with duplicated columns name

LICENSE, docs/advanced_parameters.md, docs/changelog.md, itables/javascript.py, itables/version.py
If the table fits in one page (e.g. not more than 10 rows), the search box and summary take room in the output cell but are not really useful.
After this PR, only the table will be displayed when all the conditions below are satisfied:
- the table has not more than 10 rows
- the user has not set a `dom` option
- they have not set a `lengthMenu` option, or the table rows fit in the minimum length of the menu
=> Display just the table (no search box, no summary) when the table only has a few rows

docs/changelog.md, docs/quick_start.md, itables/javascript.py, itables/version.py
Small fix to fix the rendering of empty Polars DataFrames.
Before:
_table loading_
Now:
=> Fix the rendering of empty Polars DataFrames

requirements-dev.txt
The CI failed at https://github.com/mwouts/itables/actions/runs/4688512497, saying that it could not find a version of `codecov` compatible with the other requirements.
Actually we don't use the `codecov` package - we use the GitHub action instead, so I will remove the package from the dev requirements.
=> Remove codecov from requirements-dev.txt

docs/changelog.md, docs/supported_editors.md, itables/javascript.py, itables/shiny.py, itables/version.py, tests/sample_python_apps/itables_in_a_shiny_app.py, tests/sample_python_apps/itables_in_a_shiny_app_with_tabs.py, tests/test_documentation_notebooks_run.py
=> Do not import jquery in shiny apps

docs/changelog.md, itables/sample_dfs.py, itables/version.py
Cf. https://github.com/pandas-dev/pandas/issues/55080
=> Skip timedeltas in the sample dataframes as they fail with pandas==2.1

docs/changelog.md, itables/javascript.py, itables/version.py, tests/conftest.py, tests/test_javascript.py, tests/test_json_dumps.py, tests/test_polars.py, tests/test_sample_dfs.py
In this PR we pass the `table_attributes` and `caption` directly to the `to_html` method.
This way we don't need to parse/modify the HTML generated by Styler.to_html.
Closes #199
=> Fix style in Colab

binder/postBuild, docs/advanced_parameters.md, docs/formatting.md, docs/pandas_style.md, itables/javascript.py, pyproject.toml
We need all the optional dependencies on Binders to make sure that the docs are correctly executed when rendered there.
=> Create optional dependency groups and install them on Binder

docs/changelog.md, itables/javascript.py, tests/test_pandas_style.py
Use the same layout adjusment everywhere
Closes #259
=> Use the same layout when displaying Pandas style objects

.gitignore, docs/changelog.md, environment.yml, packages/dt_for_itables/package.json, packages/itables_for_streamlit/README.md, packages/itables_for_streamlit/package-lock.json, packages/itables_for_streamlit/package.json, packages/itables_for_streamlit/public/index.html, packages/itables_for_streamlit/src/index.tsx, packages/itables_for_streamlit/tsconfig.json, packages/package-lock.json, packages/package.json, pyproject.toml, src/itables/datatables_format.py, src/itables/javascript.py, src/itables/streamlit.py, src/itables/version.py, tests/test_documentation_notebooks_run.py, tests/test_extension_arguments.py
The purpose of this PR is to provide a component that would display a DataFrame in a [streamlit](https://streamlit.io/) app.
The first version of the component could have the following limitations:
- complex columns would not be supported
- custom JS code would not be supported
- the component does not return any data from the JS side (rows selected etc won't be accessible yet)
TODO:
=> Provide a streamlit component for ITables

README.md, docs/_toc.yml, docs/advanced_parameters.md, docs/contributing.md, docs/custom_css.md, docs/dash.md, docs/extensions.md, docs/formatting.md, docs/html_export.md, docs/ipywidgets.md, docs/pandas_style.md, docs/quarto.md, docs/quick_start.md, docs/shiny.md, docs/streamlit.md, docs/supported_editors.md, docs/troubleshooting.md, src/itables/javascript.py, src/itables/options.py, src/itables/version.py, tests/test_datatables_format.py, tests/test_extension_arguments.py
=> Document the Streamlit extension

docs/changelog.md, src/itables/javascript.py, src/itables/version.py
=> Explicit encoding argument in read_text()

docs/advanced_parameters.md, docs/changelog.md, docs/extensions.md, packages/dt_for_itables/CHANGELOG.md, packages/dt_for_itables/package-lock.json, packages/dt_for_itables/package.json, packages/dt_for_itables/src/index.css, packages/dt_for_itables/src/index.js, packages/itables_for_streamlit/package-lock.json, src/itables/html/datatables_template.html, src/itables/javascript.py, src/itables/utils.py, tests/test_javascript.py
=> Add the column visibility button

.github/workflows/continuous-integration.yml, README.md, docs/advanced_parameters.md, docs/changelog.md, docs/custom_css.md, docs/polars_dataframes.md, docs/quick_start.md, docs/streamlit.md, environment.yml, packages/dt_for_itables/CHANGELOG.md, packages/dt_for_itables/package-lock.json, packages/dt_for_itables/package.json, packages/dt_for_itables/src/index.css, packages/itables_for_streamlit/package-lock.json, packages/itables_for_streamlit/src/index.tsx, src/itables/javascript.py, src/itables/options.py, src/itables/sample_dfs.py, src/itables/utils.py, src/itables/version.py, tests/test_datatables_format.py, tests/test_extension_arguments.py
This change improves the rendering of wide tables. 
The horizontal scroll bar appears on the table itself, meaning that the search and pagination control remain visible as we scroll. 
Thanks to this change, we get a more uniform rendering among Jupyter, Jupyter Book, VS Code and Streamlit.
=> Trigger an horizontal scroll through on overflow

docs/changelog.md, src/itables/datatables_format.py, src/itables/sample_dfs.py, src/itables/version.py
=> fix an OverflowError when showing pl.UInt64 values

docs/changelog.md, src/itables/sample_dfs.py, tests/sample_python_apps/itables_in_a_shiny_app.py, tests/sample_python_apps/itables_in_a_shiny_app_with_tabs.py
Cf. https://github.com/pola-rs/polars/issues/18130
=> Fix the generation of the "multiindex" polars df

docs/_toc.yml, docs/changelog.md, docs/dark_mode.md, src/itables/html/init_datatables.html, src/itables/version.py, tests/test_connected_notebook_is_small.py
=> Improve dark mode support

docs/changelog.md, packages/dt_for_itables/CHANGELOG.md, packages/dt_for_itables/README.md, packages/dt_for_itables/package-lock.json, packages/dt_for_itables/package.json, packages/dt_for_itables/src/index.js, packages/itables_for_streamlit/package-lock.json, src/itables/utils.py, src/itables/version.py
=> Add the datetime extension

.github/workflows/publish-book.yml, docs/_toc.yml, docs/extensions.md, docs/ipywidgets.md, docs/select.md
- Install the widget dependencies
- Move the row selection to a new chapter
=> Update the documentation

docs/extensions.md
I think it is useful to demonstrate how to choose which columns to use for the search pane, which is done by adding the a "columns" entry to the searchPanes dictionary.
=> Add column choice to searchPanes example

docs/changelog.md, src/itables/javascript.py, src/itables/shiny.py, src/itables/version.py, src/itables/widget/__init__.py
This makes `interactive_table` (the streamlit component) work when no `selected_rows` is passed.
=> Version 2.2.1

docs/changelog.md, src/itables/html/datatables_template.html, src/itables/javascript.py, src/itables/version.py
=> Call `new DataTable` on tables only

docs/changelog.md, src/itables/html/column_filters/pre_dt_code.js, src/itables/javascript.py, src/itables/version.py
Prior to this, the table footer would go outside of the table when exporting the notebook to HTML
=> Fix issue with tfoot not working in (Jupyter) HTML export

.gitattributes
The intent is to help linguist figure out that ITables is mostly made of Python and Javascript code
=> Mark Jupyter Notebooks as documentation

src/itables/datatables_format.py
This PR is to implement one of Marco's suggestions: 
https://github.com/mwouts/itables/pull/339#discussion_r1863898045
=> Perf improvement on Polars

.github/workflows/continuous-integration.yml, environment.yml, pyproject.toml
This PR is a follow-up on #358 - it fixes the inclusion of the `itables_for_dash` package in the sdist and wheel.
=> Add `itables_for_dash` to the wheel and sdist

docs/changelog.md, src/itables/javascript.py, tests/test_javascript.py
=> Allow a final semicolon in style strings

src/itables/javascript.py
This small PR fixes the missing exceptions in `src/itables/javascript.py`.
=> Fix missing exceptions

apps/marimo/column_visibility.py, apps/marimo/search_panes.py, apps/marimo/selected_rows.py, apps/marimo/widget.py, docs/apps/marimo.md, docs/changelog.md, docs/py/apps/marimo.py, packages/dt_for_itables/CHANGELOG.md, packages/dt_for_itables/add_host_to_root.py, packages/dt_for_itables/package.json, packages/dt_for_itables/src/index.css, packages/dt_for_itables/src/index.js, packages/dt_for_itables/test_add_host_to_root.py, packages/itables_anywidget/js/widget.css, packages/itables_anywidget/js/widget.ts, packages/itables_anywidget/package.json
This PR implements a change suggested by @mscolnick in this [comment](https://github.com/marimo-team/marimo/discussions/3192#discussioncomment-13225781).
While the change makes complete sense, and does set the `._css` attribute on the Jupyter widget as expected, it does not yet fix the issues seen in Marimo with v2.4.0, that is #383 and #387 .
Myles, sorry for asking, but the fact is that I know too little about CSS and shadow dom. Do you see what else I need to change on the `._css` field to make this work? In this simple example I would expect selected rows to appear in blue, but they don't:
Notes to myself:
=> Move the CSS imports to .css files

docs/changelog.md, src/itables/javascript.py, src/itables/version.py, tests/test_javascript.py
=> Fix: index not shown when polars is not installed

.github/workflows/continuous-integration.yml, docs/changelog.md, docs/options/buttons.md, docs/options/classes.md, docs/options/column_control.md, docs/options/options.md, docs/py/options/buttons.py, docs/py/options/classes.py, docs/py/options/column_control.py, docs/py/options/options.py, pyproject.toml, src/itables/config.py, src/itables/options.py, tests/test_config.py
=> ITables can use an `itables.toml` configuration file

docs/options/options.md, docs/py/options/options.py, src/itables/__init__.py, src/itables/config.py, src/itables/show_config.py, tests/conftest.py, tests/test_config.py, tests/test_show_config.py
The location and content of the ITables configuration file corresponding to a given directory is given by `python -m itables.show_config`.
=> More details on the configuration file

.github/codecov.yml, .github/workflows/continuous-integration.yml, packages/dt_for_itables/add_host_to_root.py, packages/dt_for_itables/test_add_host_to_root.py, tests/test_documentation_notebooks_run.py
This PR adds a few tests that should help restoring a higher coverage
=> Increase coverage

docs/changelog.md, pyproject.toml, src/itables/config.py, src/itables/version.py
My attempt to add `tomli` as a (conditional) dependency to the conda package failed at https://github.com/mwouts/itables-feedstock/, so I will make it an optional dependency instead.
=> Turn tomli into an optional dependency
